/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  theme: {
    extend: {
      fontFamily: {
        'sans': ['Cairo', 'Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        "headline": ["Cairo", "Plus Jakarta Sans"],
        "body": ["Inter", "Cairo"],
        "label": ["Inter", "Cairo"]
      },
      colors: {
        primary: "#127C8C",
        "primary-dark": "#0E5F6B",
        "accent-orange": "#f97316",
        "background-light": "#f6f8f8",
        "background-dark": "#111f21",
        zadna: {
          primary: "#127C8C",
          primaryDark: "#0E5F6B",
          primaryLight: "#1FA3B5",
          accent: "#e48215",
          accentDark: "#c16d0f",
          accentLight: "#f2a145",
          bgLight: "#F6FAFB",
          bgDark: "#0F172A",
          surfaceLight: "#FFFFFF",
          surfaceDark: "#1E293B"
        },
        "surface-container-high": "#e6e8ea",
        "inverse-surface": "#2d3133",
        "on-secondary-fixed-variant": "#2d4b52",
        "on-secondary-fixed": "#001f25",
        "on-primary-container": "#e6faff",
        "primary-fixed-dim": "#7dd3e5",
        "outline": "#6e797b",
        "secondary-fixed-dim": "#acccd3",
        "secondary-container": "#c5e5ed",
        "on-background": "#191c1e",
        "inverse-on-surface": "#eff1f3",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#bec8cb",
        "surface-variant": "#e0e3e5",
        "surface-container-highest": "#e0e3e5",
        "on-tertiary-fixed-variant": "#6d3902",
        "secondary-fixed": "#c8e8f0",
        "primary-fixed": "#a1efff",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-tertiary-fixed": "#2f1500",
        "on-surface": "#191c1e",
        "tertiary": "#834a14",
        "primary": "#00626f",
        "surface-bright": "#f7f9fb",
        "on-primary-fixed-variant": "#004e5a",
        "surface-dim": "#d8dadc",
        "on-tertiary-container": "#fff4ee",
        "tertiary-fixed": "#ffdcc3",
        "surface-container": "#eceef0",
        "secondary": "#45636a",
        "on-error-container": "#93000a",
        "error": "#ba1a1a",
        "surface-container-low": "#f2f4f6",
        "on-secondary": "#ffffff",
        "tertiary-container": "#a0622b",
        "surface": "#f7f9fb",
        "background": "#f7f9fb",
        "primary-container": "#127c8c",
        "inverse-primary": "#7dd3e5",
        "on-surface-variant": "#3e484b",
        "on-primary": "#ffffff",
        "on-secondary-container": "#49676e",
        "surface-tint": "#006876",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#001f25",
        "tertiary-fixed-dim": "#ffb77e"

      },
      keyframes: {
        'puzzle-left': {
          '0%': { transform: 'translateX(-150px) scale(0.9) rotate(-15deg)', filter: 'blur(20px)', opacity: '0' },
          '60%': { transform: 'translateX(10px) scale(1.02)', filter: 'blur(0)', opacity: '1' },
          '100%': { transform: 'translateX(0) scale(1) rotate(0)', opacity: '1' },
        },
        'puzzle-right': {
          '0%': { transform: 'translateX(150px) scale(0.9) rotate(15deg)', filter: 'blur(20px)', opacity: '0' },
          '60%': { transform: 'translateX(-10px) scale(1.02)', filter: 'blur(0)', opacity: '1' },
          '100%': { transform: 'translateX(0) scale(1) rotate(0)', opacity: '1' },
        },
        'puzzle-up': {
          '0%': { transform: 'translateY(60px) scale(0.95)', filter: 'blur(10px)', opacity: '0' },
          '70%': { transform: 'translateY(-5px) scale(1.01)', filter: 'blur(0)', opacity: '1' },
          '100%': { transform: 'translateY(0) scale(1)', opacity: '1' },
        },
        'puzzle-down': {
          '0%': { transform: 'translateY(-60px) scale(0.95)', filter: 'blur(10px)', opacity: '0' },
          '70%': { transform: 'translateY(5px) scale(1.01)', filter: 'blur(0)', opacity: '1' },
          '100%': { transform: 'translateY(0) scale(1)', opacity: '1' },
        },
        'fade-in-up': {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'puzzle-scale-rotate': {
          '0%': { transform: 'scale(0.4) rotate(-20deg)', opacity: '0', filter: 'blur(30px) brightness(1.5)' },
          '60%': { transform: 'scale(1.08) rotate(2deg)', opacity: '0.8', filter: 'blur(0)' },
          '100%': { transform: 'scale(1) rotate(0)', opacity: '1' },
        },
        'slow-float': {
          '0%, 100%': { transform: 'translate(0, 0) scale(1)' },
          '33%': { transform: 'translate(30px, -50px) scale(1.1)' },
          '66%': { transform: 'translate(-20px, 20px) scale(0.95)' },
        }
      },
      animation: {
        'puzzle-left': 'puzzle-left 0.5s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'puzzle-right': 'puzzle-right 0.5s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'puzzle-up': 'puzzle-up 0.4s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'puzzle-down': 'puzzle-down 0.4s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'fade-in-up': 'fade-in-up 0.3s ease-out forwards',
        'puzzle-scale-rotate': 'puzzle-scale-rotate 0.8s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'slow-float': 'slow-float 20s ease-in-out infinite',
      }
    },
  },
  plugins: [],
}
